DIR = graphic

CC = g++

SRC = draw.cpp transform.cpp

CCFLAGS = -g -Wall

default:
	@echo $(info -> Compiling: $(DIR))
	@$(CC) -c $(CCFLAGS) $(SRC)

clean:
	@echo $(info -> Cleaning: $(DIR))
	@$(RM) *.o
